apiVersion: "spec.keptn.sh/0.2.3"
kind: "Shipyard"
metada:
  name: "shipyard-delivery"
spec:
  stages:
    - name: "loadtest"
      sequences:
        - name: "loadtest-execution"
          tasks:
            - name: "test"
        - name: "loadtest-evaluation"
          tasks:
            - name: "evaluation"
              properties:
                timeframe: 10m
        - name: "loadtest-execution-and-evaluation"
          tasks:
            - name: "test"
            - name: "evaluation"
