apiVersion: v2
actions:
  - name: "LoadTest Execution"
    events:
      - name: "sh.keptn.event.test.triggered"

    tasks:
      - name: "Jmeter tests started"
        resources:
          limits:
            cpu: 1
            memory: 1028Mi
          requests:
            cpu: 100m
            memory: 256Mi
        maxPollDuration: 3600

        files:
          - /jmeter
          - /jmeter_plugins
        image: "docker.io/jjustb4/jmeter:5.5"
        args:
          - '-n'
          - '-t'
          - '/keptn/jmeter/blazedemo.jmx'
          - '-Jtest_length=600'
          - 'Jramp_up_period=60'
          - 'JQPS=600'
          - 'JThread=20'
          - '-j'
          - '/keptn/jmeter/test.log'
          - '-l'
          - '/keptn/jmeter/log.tlf'
          - '-Juser.classpath=/keptn/jmeter_plugins'
          - '-Jprometheus.port=8080'
          - '-Jprometheus.ip=0.0.0.0'
          - '-LINFO'
        ttlSecondsAfterFinished: 600
          
